apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: mustafazafar/admin:latest
          ports:
            - containerPort: 5173
          readinessProbe:
            httpGet:
              path: /
              port: 5173