apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: mustafazafar/backend:latest
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet: { path: /health, port: 4000 }
